<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [2]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [3]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [6]:
%%sql

SELECT
  orderdate,
  quantity,
  netprice,
  CASE
    WHEN quantity >= 2 AND netprice >= 100 THEN 'multiple high value items'
    WHEN netprice >= 100 THEN 'single high value item'
    WHEN quantity >= 2 THEN 'multiple standard items'
    ELSE 'single standard item'
  END AS order_type
FROM
  sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97       single standard item
1  2015-01-01         1    659.78     single high value item
2  2015-01-01         2     54.38    multiple standard items
3  2015-01-01         4    286.69  multiple high value items
4  2015-01-01         7    135.75  multiple high value items
5  2015-01-01         3    434.30  multiple high value items
6  2015-01-01         1     58.73       single standard item
7  2015-01-01         3     74.99    multiple standard items
8  2015-01-01         2    113.57  multiple high value items
9  2015-01-01         1    499.45     single high value item

In [9]:
%%sql

SELECT
    percentile_cont(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
FROM
    sales s
WHERE
  s.orderdate BETWEEN '2022-01-01' AND '2023-12-31';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  398.00

In [20]:
%%sql
WITH median_value AS (
  SELECT
    percentile_cont(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
  FROM
    sales s
  WHERE
    s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'
    ),
    sales_with_revenue AS (
  SELECT
    s.*,
    (s.quantity * s.netprice * s.exchangerate) AS revenue
  FROM
    sales s
  )
SELECT
    p.categoryname AS category,
    SUM(CASE WHEN sr.revenue < (SELECT median FROM median_value)
              AND sr.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
              THEN sr.revenue END) AS low_net_revenue_2022,
    SUM(CASE WHEN sr.revenue >= (SELECT median FROM median_value)
              AND sr.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
              THEN sr.revenue END) AS high_net_revenue_2022,
    SUM(CASE WHEN sr.revenue < (SELECT median FROM median_value)
              AND sr.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
              THEN sr.revenue END) AS low_net_revenue_2023,
    SUM(CASE WHEN sr.revenue >= (SELECT median FROM median_value)
              AND sr.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
              THEN sr.revenue END) AS high_net_revenue_2023
FROM
    sales_with_revenue sr
    LEFT JOIN product p ON sr.productkey = p.productkey
GROUP BY
    p.categoryname
ORDER BY
    p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87