<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [15]:
%%sql
WITH customer_orders AS (
SELECT
  customerkey,
  quantity * netprice * exchangerate AS order_value,
  COUNT(*) OVER (PARTITION BY customerkey) AS orders_per_customer
FROM
  sales
)
SELECT
  customerkey,
  AVG(order_value) AS avg_order_value_this_customer
FROM
  customer_orders
GROUP BY
  customerkey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey  avg_order_value_this_customer
0           876049                        1300.57
1          2089398                          98.39
2           418360                         289.22
3          1128199                         159.62
4          1279691                         955.34
...            ...                            ...
49482        53347                        1231.19
49483      1110282                        1192.19
49484       560047                         523.33
49485      2033110                        1155.89
49486      1603477                         136.62

[49487 rows x 2 columns]

In [20]:
%%sql

WITH yearly_cohort AS (
SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
  SUM(quantity * netprice * exchangerate) AS customer_ltv
FROM
  sales
GROUP BY
  customerkey
)
SELECT
  *,
  AVG(customer_ltv) OVER (PARTITION BY cohort_year) AS avg_cohort_ltv
FROM
  yearly_cohort

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  avg_cohort_ltv
0          1157352        2015       3099.74         5271.59
1           959501        2015          6.43         5271.59
2           894672        2015       2383.76         5271.59
3           319567        2015       5007.93         5271.59
4          1183991        2015        653.60         5271.59
...            ...         ...           ...             ...
49482       969679        2024       6333.71         2037.55
49483      1079536        2024        656.83         2037.55
49484      1926567        2024        415.14         2037.55
49485       588776        2024        236.98         2037.55
49486       752057        2024        502.60         2037.55

[49487 rows x 4 columns]

In [29]:
%%sql

SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year
FROM
  sales
WHERE
  orderdate >= '2020-01-01'
GROUP BY
  customerkey
order by
  customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey cohort_year
0           15        2021
1          180        2023
2          387        2021
3          406        2021
4          545        2023
5          649        2022
6          688        2023
7          864        2020
8          957        2022
9          963        2023

In [28]:
%%sql

SELECT
  customerkey,
  EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey)) AS cohort_year
FROM
  sales
WHERE
  orderdate >= '2020-01-01'
ORDER BY
  customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey cohort_year
0           15        2021
1          180        2023
2          180        2023
3          387        2021
4          387        2021
5          387        2021
6          387        2021
7          387        2021
8          406        2021
9          406        2021

In [8]:
%%sql

SELECT
  customerkey,
  orderdate,
  quantity * netprice * exchangerate AS net_revenue,
  COUNT(*) OVER (
    PARTITION BY customerkey
    ORDER BY orderdate) AS running_order_count,
  AVG(quantity * netprice * exchangerate) OVER (
    PARTITION BY customerkey
    ORDER BY orderdate) AS running_avg_revenue
FROM
  sales
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_avg_revenue
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,1913.55,3,836.74
3,180,2023-08-28,71.36,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
5,243,2016-05-19,287.67,1,287.67
6,387,2018-12-21,45.62,4,592.64
7,387,2018-12-21,1608.10,4,592.64
8,387,2018-12-21,619.77,4,592.64
9,387,2018-12-21,97.05,4,592.64

In [15]:
%%sql

WITH sales_with_row_number AS (
SELECT
  ROW_NUMBER() OVER (
    PARTITION BY orderdate
    ORDER BY orderdate, orderkey, linenumber
  ) AS row_number,
  *
FROM
  sales
)
SELECT *
FROM sales_with_row_number
WHERE orderdate >= '2015-01-02'
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,row_number,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
1,2,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
2,3,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
3,4,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
4,5,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
5,6,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
6,7,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
7,8,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
8,1,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
9,2,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00

In [21]:
%%sql

SELECT
  customerkey,
  COUNT(*) AS total_orders,
  ROW_NUMBER() OVER (ORDER BY COUNT(*) DESC) AS total_orders_row_number,
  RANK() OVER (ORDER BY COUNT(*) DESC) AS total_orders_rank,
  DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS total_orders_dense_rank
FROM
  sales
GROUP BY
  customerkey
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_orders,total_orders_row_number,total_orders_rank,total_orders_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,759419,24,8,8,6
8,1427444,24,9,8,6
9,1876222,24,10,8,6

In [28]:
%%sql

SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM
  sales
WHERE
  EXTRACT(YEAR FROM orderdate) = 2023
GROUP BY
  order_month
ORDER BY
  order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

   order_month  net_revenue
0      2023-01   3664431.34
1      2023-02   4465204.57
2      2023-03   2244316.52
3      2023-04   1162796.16
4      2023-05   2943005.99
5      2023-06   2864500.03
6      2023-07   2337639.34
7      2023-08   2623919.79
8      2023-09   2622774.85
9      2023-10   2551322.61
10     2023-11   2700103.38
11     2023-12   2928550.93

In [34]:
%%sql
WITH monthly_rev AS (
SELECT
  TO_CHAR(orderdate, 'YYYY-MM') AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue
FROM
  sales
WHERE
  EXTRACT(YEAR FROM orderdate) = 2023
GROUP BY
  order_month
ORDER BY
  order_month
)
SELECT
  *,
  FIRST_VALUE(net_revenue) OVER (ORDER BY order_month) AS first_month_revenue,
  LAST_VALUE(net_revenue) OVER (ORDER BY order_month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_month_revenue,
  NTH_VALUE(net_revenue, 5) OVER (ORDER BY order_month ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS fifth_month_revenue,
  LAG(net_revenue) OVER (ORDER BY order_month) AS previous_month_revenue,
  LEAD(net_revenue) OVER (ORDER BY order_month) AS next_month_revenue,
  net_revenue - LAG(net_revenue) OVER (ORDER BY order_month) AS revenue_diff_from_previous_month,
  net_revenue - FIRST_VALUE(net_revenue) OVER (ORDER BY order_month) AS revenue_diff_from_first_month
FROM
  monthly_rev

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,order_month,net_revenue,first_month_revenue,last_month_revenue,fifth_month_revenue,previous_month_revenue,next_month_revenue,revenue_diff_from_previous_month,revenue_diff_from_first_month
0,2023-01,3664431.34,3664431.34,2928550.93,2943005.99,NaN,4465204.57,NaN,0.00
1,2023-02,4465204.57,3664431.34,2928550.93,2943005.99,3664431.34,2244316.52,800773.22,800773.22
2,2023-03,2244316.52,3664431.34,2928550.93,2943005.99,4465204.57,1162796.16,-2220888.05,-1420114.82
3,2023-04,1162796.16,3664431.34,2928550.93,2943005.99,2244316.52,2943005.99,-1081520.36,-2501635.18
4,2023-05,2943005.99,3664431.34,2928550.93,2943005.99,1162796.16,2864500.03,1780209.83,-721425.36
5,2023-06,2864500.03,3664431.34,2928550.93,2943005.99,2943005.99,2337639.34,-78505.96,-799931.32
6,2023-07,2337639.34,3664431.34,2928550.93,2943005.99,2864500.03,2623919.79,-526860.69,-1326792.00
7,2023-08,2623919.79,3664431.34,2928550.93,2943005.99,2337639.34,2622774.85,286280.45,-1040511.55
8,2023-09,2622774.85,3664431.34,2928550.93,2943005.99,2623919.79,2551322.61,-1144.94,-1041656.50
9,2023-10,2551322.61,3664431.34,2928550.93,2943005.99,2622774.85,2700103.38,-71452.24,-1113108.74
10,2023-11,2700103.38,3664431.34,2928550.93,2943005.99,2551322.61,2928550.93,148780.78,-964327.96
11,2023-12,2928550.93,3664431.34,2928550.93,2943005.99,2700103.38,NaN,228447.54,-735880.42