<a href="https://colab.research.google.com/github/anitakehinde/COVID19dataexplorationsql/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

SELECT table_name
FROM information_schema.tables
WHERE table_schema='public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [3]:
%%sql
WITH median_value AS (
  SELECT
    percentile_cont(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS median
  FROM
    sales s
  WHERE
    s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'
    ),
    sales_with_revenue AS (
  SELECT
    s.*,
    (s.quantity * s.netprice * s.exchangerate) AS revenue
  FROM
    sales s
  )
SELECT
    p.categoryname AS category,
    SUM(CASE WHEN sr.revenue < (SELECT median FROM median_value)
              AND sr.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
              THEN sr.revenue END) AS low_net_revenue_2022,
    SUM(CASE WHEN sr.revenue >= (SELECT median FROM median_value)
              AND sr.orderdate BETWEEN '2022-01-01' AND '2022-12-31'
              THEN sr.revenue END) AS high_net_revenue_2022,
    SUM(CASE WHEN sr.revenue < (SELECT median FROM median_value)
              AND sr.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
              THEN sr.revenue END) AS low_net_revenue_2023,
    SUM(CASE WHEN sr.revenue >= (SELECT median FROM median_value)
              AND sr.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
              THEN sr.revenue END) AS high_net_revenue_2023
FROM
    sales_with_revenue sr
    LEFT JOIN product p ON sr.productkey = p.productkey
GROUP BY
    p.categoryname
ORDER BY
    p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue_2022,high_net_revenue_2022,low_net_revenue_2023,high_net_revenue_2023
0,Audio,222337.83,544600.39,180251.13,508439.06
1,Cameras and camcorders,133004.54,2249528.02,104869.46,1878676.83
2,Cell phones,814449.53,7305215.55,729699.39,5272448.24
3,Computers,624340.42,17237873.07,590790.31,11060076.90
4,Games and Toys,231979.63,84147.67,206103.36,64271.60
5,Home Appliances,219797.07,6392649.61,176261.35,5743731.52
6,"Music, Movies and Audio Books",685808.49,2303488.80,574958.76,1605809.37
7,TV and Video,272338.29,5542998.32,164275.35,4247902.87

In [16]:
%%sql
WITH percentiles AS (
  SELECT
    percentile_cont(0.25) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS rev_25th_percentile,
    percentile_cont(0.75) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) AS rev_75th_percentile
  FROM
    sales s
  WHERE
    s.orderdate BETWEEN '2022-01-01' AND '2023-12-31'
)
SELECT
    p.categoryname AS category,
    CASE
        WHEN (S.quantity * s.netprice * s.exchangerate) <= pctl.rev_25th_percentile THEN '3_low_net_revenue'
        WHEN (S.quantity * s.netprice * s.exchangerate) >= pctl.rev_75th_percentile THEN '1_high_net_revenue'
        ELSE '2_medium_net_revenue'
    END AS revenue_tier,
    SUM(S.quantity * s.netprice * s.exchangerate) AS total_revenue
FROM
    sales s
    LEFT JOIN product p ON s.productkey = p.productkey,
    percentiles pctl
GROUP BY
    p.categoryname,
    revenue_tier
ORDER BY
    p.categoryname, revenue_tier

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                         category          revenue_tier  total_revenue
0                           Audio    1_high_net_revenue     1213265.71
1                           Audio  2_medium_net_revenue     3832415.38
2                           Audio     3_low_net_revenue      267217.01
3         Cameras and camcorders     1_high_net_revenue    15050781.63
4         Cameras and camcorders   2_medium_net_revenue     3388546.10
5         Cameras and camcorders      3_low_net_revenue       81032.92
6                     Cell phones    1_high_net_revenue    21874993.15
7                     Cell phones  2_medium_net_revenue    10338963.22
8                     Cell phones     3_low_net_revenue      410309.35
9                       Computers    1_high_net_revenue    79607760.89
10                      Computers  2_medium_net_revenue    10808054.11
11                      Computers     3_low_net_revenue      203207.06
12                 Games and Toys    1_high_net_revenue      133749.09
13                 Games and Toys  2_medium_net_revenue     1001381.91
14                 Games and Toys     3_low_net_revenue      533443.13
15                Home Appliances    1_high_net_revenue    22383475.30
16                Home Appliances  2_medium_net_revenue     4118724.64
17                Home Appliances     3_low_net_revenue      105045.60
18  Music, Movies and Audio Books    1_high_net_revenue     3844996.29
19  Music, Movies and Audio Books  2_medium_net_revenue     6100817.99
20  Music, Movies and Audio Books     3_low_net_revenue      642496.71
21                   TV and Video    1_high_net_revenue    16632856.33
22                   TV and Video  2_medium_net_revenue     3766783.30
23                   TV and Video     3_low_net_revenue       67221.76

In [24]:
%%sql

SELECT
  DATE_TRUNC('month', orderdate)::date AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS num_customers
FROM sales
GROUP BY order_month
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_month  net_revenue  num_customers
0  2015-01-01    384092.66            200
1  2015-02-01    706374.12            291
2  2015-03-01    332961.59            139
3  2015-04-01    160767.00             78
4  2015-05-01    548632.63            236
5  2015-06-01    748563.97            238
6  2015-07-01    635376.13            227
7  2015-08-01    718538.62            235
8  2015-09-01    696805.68            277
9  2015-10-01    824891.22            304

In [25]:
%%sql

SELECT
  EXTRACT(YEAR FROM orderdate) AS order_year,
  EXTRACT(MONTH FROM orderdate) AS order_month,
  SUM(quantity * netprice * exchangerate) AS net_revenue,
  COUNT(DISTINCT customerkey) AS num_customers
FROM sales
GROUP BY order_month, order_year
ORDER BY order_year, order_month
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  order_year order_month  net_revenue  num_customers
0       2015           1    384092.66            200
1       2015           2    706374.12            291
2       2015           3    332961.59            139
3       2015           4    160767.00             78
4       2015           5    548632.63            236
5       2015           6    748563.97            238
6       2015           7    635376.13            227
7       2015           8    718538.62            235
8       2015           9    696805.68            277
9       2015          10    824891.22            304

In [26]:
%%sql

SELECT CURRENT_DATE

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2025-10-08